using System.Collections;
using System.Collections.Generic;
using UnityEngine;
/// <summary>
/// this is gonna be reponsible for reading an xml or text file...
/// rolling for loot items based on simple rng...
/// rolling for X num of those loot items based on simple rng....
/// childing deactivated loot objects to a Loot parent...
/// all before mom and dad come home...
/// ...
/// *chris angel voice* are you ready?
/// </summary>
public class LootManager : MonoBehaviour 
{

}
